"""add address, phone, change book price and add book details unique constraint

Revision ID: b6424b6436e8
Revises: ba02c178a283
Create Date: 2025-07-31 16:34:09.704813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6424b6436e8'
down_revision: Union[str, Sequence[str], None] = 'ba02c178a283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_book_status', 'book_details', ['book_id', 'status'])
    op.alter_column('books', 'price',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=False)
    op.add_column('orders', sa.Column('address', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('return_orders', sa.Column('address', sa.String(), nullable=False))
    op.add_column('return_orders', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_orders', 'phone_number')
    op.drop_column('return_orders', 'address')
    op.drop_column('orders', 'phone_number')
    op.drop_column('orders', 'address')
    op.alter_column('books', 'price',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=False)
    op.drop_constraint('uq_book_status', 'book_details', type_='unique')
    # ### end Alembic commands ###
