"""adding reset_token and reset_token_expires_at

Revision ID: ba02c178a283
Revises: 606ad18714f3
Create Date: 2025-07-30 12:19:57.887162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba02c178a283'
down_revision: Union[str, Sequence[str], None] = '606ad18714f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promo_code_accounts')
    op.add_column('borrow_order_books', sa.Column('promo_code_discount', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('borrow_order_books', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('borrow_order_books_promo_code_id_fkey'), 'borrow_order_books', type_='foreignkey')
    op.create_foreign_key(None, 'borrow_order_books', 'users', ['user_id'], ['id'])
    op.drop_column('borrow_order_books', 'promo_code_id')
    op.add_column('orders', sa.Column('promo_code_id', sa.Integer(), nullable=True))
    op.create_index('ix_user_promo_code', 'orders', ['user_id', 'promo_code_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'promo_codes', ['promo_code_id'], ['id'])
    op.add_column('purchase_order_books', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'purchase_order_books', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['reset_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'reset_token_expires_at')
    op.drop_column('users', 'reset_token')
    op.drop_constraint(None, 'purchase_order_books', type_='foreignkey')
    op.drop_column('purchase_order_books', 'user_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index('ix_user_promo_code', table_name='orders')
    op.drop_column('orders', 'promo_code_id')
    op.add_column('borrow_order_books', sa.Column('promo_code_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'borrow_order_books', type_='foreignkey')
    op.create_foreign_key(op.f('borrow_order_books_promo_code_id_fkey'), 'borrow_order_books', 'promo_codes', ['promo_code_id'], ['id'])
    op.drop_column('borrow_order_books', 'user_id')
    op.drop_column('borrow_order_books', 'promo_code_discount')
    op.create_table('promo_code_accounts',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('promo_code_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], name=op.f('promo_code_accounts_promo_code_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('promo_code_accounts_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'promo_code_id', name=op.f('promo_code_accounts_pkey'))
    )
    # ### end Alembic commands ###
