from .users import add_dummy_users
from .authors import add_dummy_authors
from .categories import add_dummy_categories
from .books import add_dummy_books
from .book_details import add_dummy_book_details
from .cart import add_dummy_cart_items
from .promo_codes import add_dummy_promo_codes
from .orders import add_dummy_orders
from .return_orders import add_dummy_return_orders
from .purchase_orders import add_dummy_purchase_orders
from .borrow_orders import add_dummy_borrow_orders
from .settings import add_dummy_settings
